path: F:/github/ultralytics-main/datasets/pipeline_defect
train: images/train
val: images/val
nc: 6
names: 
  0: Deformation
  1: Obstacle
  2: Rupture
  3: Disconnect
  4: Misalignment
  5: Deposition


